# ========================
# app Deployment
# ========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: safalmaitri/kyma-demo-media-library:latest
        envFrom:
        - secretRef:
            name: app-env
        ports:
        - containerPort: 3000
---
# ========================
# app Service
# ========================
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - name: api
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
# ========================
# APIRule for app Public Access
# ========================
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: app-api
spec:
  gateway: kyma-system/kyma-gateway
  host: app-client.a789781.kyma.ondemand.com
  service:
    name: app-service
    port: 3000
  rules:
  - path: /.*
    methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS" ]
    accessStrategies:
    - handler: allow
      config: {}
